# Generated by Django 2.0.13 on 2019-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonaccivalue',
            name='number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fibonaccivalue',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
