# Generated by Django 2.0.13 on 2019-03-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190326_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonaccivalue',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fibonaccivalue',
            name='value',
            field=models.TextField(),
        ),
    ]
